name: vision_board
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2
  crop_your_image: ^0.7.5
  flutter_svg: ^2.0.10+1
  in_app_review: ^2.0.9
  hive_flutter: ^1.1.0
  image_picker: ^1.0.8
  share_plus: ^7.2.2
  provider: ^6.1.2
  sizer: ^2.0.15
  intl: ^0.19.0
  hive: ^2.2.3
  uuid: ^4.5.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
